apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense
  labels:
    app: django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - image: ehsanrahgozar/expence-sharing:latest
          name: expense
          ports:
            - containerPort: 8000
              name: gunicorn
