version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-net
    deploy:
      resources:
        limits:
          memory: 2G
volumes:
  postgres_data:
    driver: local

networks:
  postgres-net:
    name:
      postgres-net
